services:
  - type: web
    name: owncast
    env: docker
    plan: free
    repo: https://github.com/realTimexo/owncast/
    dockerfilePath: ./Dockerfile
    region: frankfurt
    envVars:
      - key: OWNCAST_RTMP_PORT
        value: "1935"
